language: python
python:
  - "3.6"
  # - "3.7"
os:
  - linux
  # - osx
env:
  - CMIP_DATA_ROOT=/home/travis
install:
  # Python 3.x is default
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  # Install Julia
  - wget https://julialang-s3.julialang.org/bin/linux/x64/1.0/julia-1.0.3-linux-x86_64.tar.gz
  - tar xfz julia-*-linux-x86_64.tar.gz
  - sudo ln -s $(pwd)/julia-*/bin/julia /usr/bin/julia
  # Create environment (specifies python version explicitly)
  - conda env create -n c3s_magic_wps -f environment.yml
  - source activate c3s_magic_wps
  # Packages for testing
  - conda install pytest flake8
   # ESMValTool
   #  - CURWORK=$PWD
   # - cd ..
   #- git clone -b v2.0a2 https://github.com/ESMValGroup/ESMValTool.git esmvaltool
   #- cd esmvaltool
   #- pip install .
   #- cd $CURWORK
  # Install Emu WPS
  - python setup.py install
before_script:
  # Start WPS service on port 5000 on 0.0.0.0
  - c3s_magic_wps start --daemon --bind-host 0.0.0.0 --port 5000
  - sleep 2
script:
  - pytest
  - flake8
