version: '3'
services:
  copernicus:
    build: .
    image: cp4cds/copernicus-wps-demo
    ports:
      - "5000:5000"


# docker-compose build
# docker-compose up
# docker-compose down
# docker-compose rm
