wps:
  image: cp4cds/copernicus-wps-demo
  environment:
    HOSTNAME: $HOSTNAME
    HTTP_PORT: $HTTP_PORT
    OUTPUT_PORT: $OUTPUT_PORT
  ports:
    - "$HTTP_PORT:$HTTP_PORT"
    - "$OUTPUT_PORT:$OUTPUT_PORT"
#  volumes:
#    - lib:/opt/birdhouse/var/lib
#    - log:/opt/birdhouse/var/log
#  volume_driver: local
