version: '3'
services:
  wps:
    build: .
    image: c3s-magic/c3s-magic-wps
    ports:
      - "5000:5000"
    environment:
      - "WPS_OUTPUT_URL=http://localhost:5000/wps"


# docker-compose build
# docker-compose up
# docker-compose down
# docker-compose rm
