name: emu
channels:
- birdhouse
- conda-forge
- defaults
dependencies:
- python=2.7
- pyopenssl=0.16
- cryptography=1.4
- pyyaml=3.11
- curl=7.45.0
- icu=58
- lxml
# buildout
- mako
# tests
- pytest
- flake8
# wps
- pywps=4.0.0
- nginx=1.10.3
- supervisor=3.3.1
- gunicorn=19.1.0
- gevent=1.2
- lxml=3.7
- libxslt=1.1.29
#- eventlet=0.16.1
# esmvaltool
- ncl=6.4.0
- esgf-pyclient
- pip:
  - genshi==0.7
  - eventlet==0.19.0
