name: copernicus
channels:
#- esmvalgroup
- birdhouse
- conda-forge
- defaults
dependencies:
- pywps=4.1.10
- jinja2
- click
- psutil
- cdo=1.9.3 #for the zmnam recipe
- pip:
  - j2cli[yaml]
# esmvaltool
#- esmvaltool=2.0a0
