name: c3s_magic_wps
channels:
- birdhouse
- conda-forge
- defaults
dependencies:
- python=3.6
- pip
# install pywps from github for now, as it fixes a problem
# with sql logging usage
#- pywps=4.2
- jinja2
- click
- psutil
- pip:
  - j2cli
