name: copernicus-wps-demo
channels:
- birdhouse
- conda-forge
- defaults
dependencies:
- python=2.7
- pyopenssl=0.16
- cryptography=1.4
- pyyaml=3.11
- curl=7.45.0
- icu=58.1
# tests
- pytest
- flake8
- ipython
# wps
- pywps=4.0.0
- nginx=1.10.3
- supervisor=3.3.1
- gunicorn=19.7
- gevent=1.2
- eventlet=0.21
- lxml=3.7
- libxslt=1.1.29
- genshi=0.7
# helpers
- netcdf4
- cdo=1.8.2
- python-cdo
# python wrapper for ncl
#- pyngl
#- pynio
# esmvaltool
- esmvaltool=1.1.0
- mako
# drmaa scheduler
- drmaa
- dill
