name: copernicus-wps-demo
channels:
- birdhouse
- conda-forge
- conda-forge/label/broken
- defaults
dependencies:
- python=2.7
- setuptools=36.5.0
- pyopenssl=0.16
- cryptography=1.4
- curl=7.45.0
- icu=58.1
# tests
- pytest
- flake8=3.3
# wps
- pywps=4.0.0
- nginx=1.10.3
- supervisor=3.3.1
- gunicorn=19.7
- gevent=1.2
- eventlet=0.21
- lxml=3.7
- libxslt=1.1.29
- genshi=0.7
- mako
- jinja2
# helpers
#- cdo=1.8.2
#- python-cdo
# esmvaltool
- esmvaltool=2.0.0
#- ncl
# ncl patch
- poppler=0.52
- xerces-c=3.1
- gsl
# ncl patch end
