#!/bin/bash
# This rsync "script" synchronized data to a machine running the MAGIC Wps. It assumes Jasmin is the source, and DAS is the target

#Please supply the target username on the command line
#Eg. sync-data-fs0 user
TARGET_USER=$1

#Synchronize CMIP files
rsync -vhr --progress --copy-links --files-from=CMIP-SELECTION /group_workspaces/jasmin2/cp4cds1/data/c3s-cmip5/output1/ $TARGET_USER@fs0.das5.cs.vu.nl:/var/scratch2/$TARGET_USER/cp4cds/

#Also synchronize OBS files
rsync -vhr --progress --copy-links --files-from=OBS-SELECTION /group_workspaces/jasmin2/cp4cds1/data/dkrz_pool/ $TARGET_USER@fs0.das5.cs.vu.nl:/var/scratch2/$TARGET_USER/dkrz_pool/

