#!/bin/bash
# This rsync "script" synchronized data to a machine running the MAGIC Wps. It assumes Jasmin is the source, and there is a /data/ folder available on the target machine

#Please supply the target machine (with username if needed) on the command line
#Eg. sync-data user@host.domain.com 
TARGET_MACHINE=$1

#Synchronize CMIP files
rsync -avhr --progress --copy-links --files-from=CMIP-SELECTION /group_workspaces/jasmin2/cp4cds1/data/c3s-cmip5/output1/ $TARGET_MACHINE:/data/cp4cds/

#Also synchronize OBS files
rsync -avhr --progress --copy-links --files-from=OBS-SELECTION /group_workspaces/jasmin2/cp4cds1/data/dkrz_pool/ $TARGET_MACHINE:/data/dkrz_pool/

